language: java
script:
- "./gradlew build"
deploy:
  provider: heroku
  api_key:
    secure: TADxHbs+MkTpOQI4DdPGIvXkta+QGVZYNmmecLsR1avloQQLOR6e51qijgaEM5e4oBMVEsjlbPzckdfi493jPhmfkNJUdInbePqRvb6KWkGa5gFB6i9e0nuh8/4Sj2QXHmHLy5BwtlxdS0vdzyTSLX4d9sUa9f9jzP9thGTHfKklGjK/G40rDQh6vjghHb+Ec6QMm7oiiP8crYRvIf3e298xkgZY1h5qbAsqlXXjVQ5uvneuQIIhCAi4lB25aBr6+z4u/gUBB+dqGRgaIMqbN1FW2WWE0k8xRzwBbteWcH1dFKPFsqbw/O85XSkKwv5grYnHZHNpkJRJlG96Pyf06GR2ZYE4y8XBNcm9tPV++QrafzIcgmeR3nbRX2/tUGpKbKnVMaph2C8Pfe3WuQtSPcO7KfJryddTyzOWMeErF63PQSmPdGFSOXnUz5uBbYsAuTRscD5rAmEabZV8L4yGBcurZwvdZGIYDxjXkOlVYJuCxYMGQhmAEk+yZZ1+sVRNKER/gxhicSfVX9Fss8cTBPYVxDVjw4QaFnF8HNypWZhzuJSZY/+Ex5z8A6J96l9rjncAgma8V4Fj+MHBNB1N61e4EK2KPurJfDr2/iyngI3Svc5XW8V0vNpuzgPkNfN1PqbaAQFby9vs++JShKxQHZQuBO3arb95Bc0IHq1rWss=
  app:
    master: gallery-backend-01
  on: master
